/** Machine-readable codes for admin API JSON responses (`errorCode`). UI maps via t(`admin.api.${code}`). */

export const AdminApiErrorCode = {
  SITE_ID_REQUIRED: "SITE_ID_REQUIRED",
  SITE_CATEGORY_INVALID: "SITE_CATEGORY_INVALID",
  SITE_NAME_REQUIRED: "SITE_NAME_REQUIRED",
  SITE_NOT_FOUND: "SITE_NOT_FOUND",
  SITE_UPDATE_FAILED: "SITE_UPDATE_FAILED",
  SITE_CREATE_FAILED: "SITE_CREATE_FAILED",
  SITE_DELETE_FAILED: "SITE_DELETE_FAILED",
  SITES_LOAD_FAILED: "SITES_LOAD_FAILED",
  WORKER_ID_REQUIRED: "WORKER_ID_REQUIRED",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  PROFILE_LOAD_FAILED: "PROFILE_LOAD_FAILED",
  NOTHING_TO_UPDATE: "NOTHING_TO_UPDATE",
  AUTH_USER_UPDATE_FAILED: "AUTH_USER_UPDATE_FAILED",
  PROFILE_UPDATE_FAILED: "PROFILE_UPDATE_FAILED",
  DEEPL_NOT_CONFIGURED: "DEEPL_NOT_CONFIGURED",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
} as const;

export type AdminApiErrorCode = (typeof AdminApiErrorCode)[keyof typeof AdminApiErrorCode];
