/** Machine-readable codes for admin API JSON responses (`errorCode`). UI maps via t(`admin.api.${code}`). */

export const AdminApiErrorCode = {
  // Auth (shared requireUser / requireAdmin)
  AUTH_BEARER_REQUIRED: "AUTH_BEARER_REQUIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_PROFILE_MISSING: "AUTH_PROFILE_MISSING",
  AUTH_ADMIN_REQUIRED: "AUTH_ADMIN_REQUIRED",
  AUTH_WORKER_ROLE_REQUIRED: "AUTH_WORKER_ROLE_REQUIRED",

  SITE_ID_REQUIRED: "SITE_ID_REQUIRED",
  SITE_CATEGORY_INVALID: "SITE_CATEGORY_INVALID",
  SITE_NAME_REQUIRED: "SITE_NAME_REQUIRED",
  SITE_NOT_FOUND: "SITE_NOT_FOUND",
  SITE_UPDATE_FAILED: "SITE_UPDATE_FAILED",
  SITE_CREATE_FAILED: "SITE_CREATE_FAILED",
  SITE_DELETE_FAILED: "SITE_DELETE_FAILED",
  SITE_DELETE_HAS_JOBS: "SITE_DELETE_HAS_JOBS",
  SITES_LOAD_FAILED: "SITES_LOAD_FAILED",

  WORKER_ID_REQUIRED: "WORKER_ID_REQUIRED",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  PROFILE_LOAD_FAILED: "PROFILE_LOAD_FAILED",
  NOTHING_TO_UPDATE: "NOTHING_TO_UPDATE",
  AUTH_USER_UPDATE_FAILED: "AUTH_USER_UPDATE_FAILED",
  PROFILE_UPDATE_FAILED: "PROFILE_UPDATE_FAILED",
  DEEPL_NOT_CONFIGURED: "DEEPL_NOT_CONFIGURED",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",

  WORKER_SELF_DEMOTE: "WORKER_SELF_DEMOTE",
  ROLE_MUST_BE_ADMIN_OR_WORKER: "ROLE_MUST_BE_ADMIN_OR_WORKER",
  WORKER_ADMIN_DISABLE_FORBIDDEN: "WORKER_ADMIN_DISABLE_FORBIDDEN",
  WORKER_DELETE_ADMIN_FORBIDDEN: "WORKER_DELETE_ADMIN_FORBIDDEN",
  WORKER_DELETE_HAS_LOGS: "WORKER_DELETE_HAS_LOGS",
  WORKER_DELETE_HAS_JOBS: "WORKER_DELETE_HAS_JOBS",
  WORKER_DELETE_AUTH_INCOMPLETE: "WORKER_DELETE_AUTH_INCOMPLETE",

  ANONYMIZE_SELF_FORBIDDEN: "ANONYMIZE_SELF_FORBIDDEN",
  ANONYMIZE_ADMIN_FORBIDDEN: "ANONYMIZE_ADMIN_FORBIDDEN",
  /** Profile scrubbed but auth.deleteUser failed (non-404). */
  ANONYMIZE_AUTH_DELETE_PARTIAL: "ANONYMIZE_AUTH_DELETE_PARTIAL",

  ASSIGNMENTS_LOAD_FAILED: "ASSIGNMENTS_LOAD_FAILED",
  ASSIGN_ACTION_REQUIRED: "ASSIGN_ACTION_REQUIRED",
  ASSIGN_UNKNOWN_ACTION: "ASSIGN_UNKNOWN_ACTION",
  ASSIGN_SITE_ARCHIVED: "ASSIGN_SITE_ARCHIVED",
  ASSIGN_WORKER_INACTIVE: "ASSIGN_WORKER_INACTIVE",
  ASSIGN_CANNOT_ASSIGN_ADMIN: "ASSIGN_CANNOT_ASSIGN_ADMIN",

  JOB_DATE_REQUIRED: "JOB_DATE_REQUIRED",
  JOB_SCHEDULE_TIME_REQUIRED: "JOB_SCHEDULE_TIME_REQUIRED",
  WORKER_IDS_REQUIRED: "WORKER_IDS_REQUIRED",
  JOB_MINUTES_OR_HM_REQUIRED: "JOB_MINUTES_OR_HM_REQUIRED",
  JOB_TIME_LOG_ID_MISSING: "JOB_TIME_LOG_ID_MISSING",
  JOB_SCHEDULE_START_INVALID: "JOB_SCHEDULE_START_INVALID",
  TIME_LOG_STARTED_AT_INVALID: "TIME_LOG_STARTED_AT_INVALID",

  SCHEDULE_DATES_REQUIRED: "SCHEDULE_DATES_REQUIRED",
  SCHEDULE_DATES_INVALID: "SCHEDULE_DATES_INVALID",

  REPORT_PERIOD_INVALID: "REPORT_PERIOD_INVALID",
  REPORT_PERIOD_ORDER: "REPORT_PERIOD_ORDER",

  INVITE_IDENTIFIER_REQUIRED: "INVITE_IDENTIFIER_REQUIRED",
  INVITE_EMAIL_INVALID: "INVITE_EMAIL_INVALID",
  INVITE_PHONE_INVALID: "INVITE_PHONE_INVALID",
  INVITE_ROLE_INVALID: "INVITE_ROLE_INVALID",
  INVITE_USER_LOOKUP_FAILED: "INVITE_USER_LOOKUP_FAILED",
  INVITE_USER_CREATE_FAILED: "INVITE_USER_CREATE_FAILED",
  INVITE_PROFILE_FAILED: "INVITE_PROFILE_FAILED",

  ACTIVATE_ID_REQUIRED: "ACTIVATE_ID_REQUIRED",
  ACTIVATE_NOT_WORKER: "ACTIVATE_NOT_WORKER",
  ACTIVATE_REQUIREMENTS_NOT_MET: "ACTIVATE_REQUIREMENTS_NOT_MET",
  ACTIVATE_EMAIL_UNCONFIRMED: "ACTIVATE_EMAIL_UNCONFIRMED",

  JOB_DELETE_DONE_ONLY: "JOB_DELETE_DONE_ONLY",
  JOB_UPDATE_LOCKED: "JOB_UPDATE_LOCKED",
  JOB_CANCEL_USE_ENDPOINT: "JOB_CANCEL_USE_ENDPOINT",
  JOB_STATUS_INVALID: "JOB_STATUS_INVALID",
  JOB_TIME_INVALID: "JOB_TIME_INVALID",
  JOB_ID_REQUIRED: "JOB_ID_REQUIRED",
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  JOBS_LOAD_FAILED: "JOBS_LOAD_FAILED",
  ASSIGNMENTS_TABLE_MISSING: "ASSIGNMENTS_TABLE_MISSING",

  PHOTO_EMPTY: "PHOTO_EMPTY",
  PHOTO_TOO_LARGE: "PHOTO_TOO_LARGE",
  PHOTO_FORMAT_INVALID: "PHOTO_FORMAT_INVALID",
  PHOTO_LIMIT_REACHED: "PHOTO_LIMIT_REACHED",
  PHOTO_PICK_REQUIRED: "PHOTO_PICK_REQUIRED",
  PHOTO_PATH_REQUIRED: "PHOTO_PATH_REQUIRED",
  PHOTO_DELETE_FORBIDDEN: "PHOTO_DELETE_FORBIDDEN",

  DB_ERROR: "DB_ERROR",
} as const;

export type AdminApiErrorCode = (typeof AdminApiErrorCode)[keyof typeof AdminApiErrorCode];
